### ISSUE TITLE
Npm Install

### ISSUE THREAD

**Issue by diegoluizoro** [mnedelchev-vn/dxsale-sniper-bot#1]
I have this issue when I execute the command npm install

$ npm install
npm WARN deprecated querystring@0.2.0: The
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by Borkuz** [comment]
change the following in package.json
`"web3":"1.0.0-beta.36"` to `"web3":"1.4.0"`

**Comment by diegoluizoro** [comment]
Hello, thank you for the answer.

Now returned this error:

npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated multicodec@0.5.7: stable api reached

**Comment by diegoluizoro** [comment]
Now the bot started but this error happened:

One or more of the private keys are invalid.

**Comment by yyj159023** [comment]
![360截图20210709025754845](https://user-images.githubusercontent.com/36934324/124976248-96b7a780-e061-11eb-9db8-08c998b7b9ca.jpg)

**Comment by dentacoin-private** [comment]
> Now the bot started but this error happened:
> 
> One or more of the private keys are invalid.
> 
> Edit: My wallet and the project that I want to go in Dxsale is from BSC.

Hey, read more about the **_senderPrivateKey_** parameter at [https://github.com/mnedelchev-vn/dxsale-sniper-bot](https://github.com/mnedelchev-vn/dxsale-sniper-bot) it's very well described.

**Comment by mnedelchev-vn** [comment]
> Now the bot started but this error happened:
> 
> One or more of the private keys are invalid.
> 
> Edit: My wallet and the project that I want to go in Dxsale is from BSC.

Hey, read more about the **_senderPrivateKey_** [parameter at https://github.com/mnedelchev-vn/dxsale-sniper-bot](parameter at https://github.com/mnedelchev-vn/dxsale-sniper-bot) it's very well described.

**Comment by diegoluizoro** [comment]
Thank you! Now worked.

The last question its about the error message when I execute the bot but the presale didn't started yet.

I got this:  

Cronjob iteration.
Method web3.eth.estimateGas() failed. Message: Returned error: execution reverted

It´s correct? And if it's correct, where I can change this message to aother like "Waiting for the launch!"

**Comment by mnedelchev-vn** [comment]
Error message **_Method web3.eth.estimateGas() failed. Message: Returned error: execution reverted_** will be showing until DxSale presale contract is ready to accept BNBs. When the contract is ready the transaction will execute and the cronjob will stop. If you wish to edit any error messages you will have to edit the .js file by your self. I will be closing the issue now as you said you don't have any errors now.
