### ISSUE TITLE
Method web3.eth.estimateGas() failed. Message: Returned error: execution reverted

### ISSUE THREAD

**Issue by Borkuz** [mnedelchev-vn/dxsale-sniper-bot#5]
I keep getting this error, `Method web3.eth.estimateGas() failed. Message: Returned error: execution reverted`  u use gas 25, but nothing happens

**Comment by cong235** [comment]
Yeah, same question. I don't know why

**Comment by mnedelchev-vn** [comment]
@Borkuz @cong235 Hi, this message means that the Presale contract is not yet ready to accept BNB payments :) It does not mean that there is something wrong on your end, as you know DxSale have a timer which is counting until the presale contract is ready to accept payments. I changed the error message with another which makes it more clear that the transaction cannot be fired yet. Closing the issue.

**Comment by cong235** [comment]
> Hi, this message means that the Presale contract is not yet ready to accept BNB payments :) It does not mean that there is something wrong on your end, as you know DxSale have a timer which is counting until the presale contract is ready to accept payments. I changed the error message with another which makes it more clear that the transaction cannot be fired yet. Closing the issue.

I were test with this presale link.
And our tool cant buy it. Can you test by yourself with some other presale same like that?
https://dxsale.app/app/v2_9/defipresale?saleID=1041&chain=BSC
