### ISSUE TITLE
Please assist with solution to this npm installation error

### ISSUE THREAD

**Issue by allenken7** [mnedelchev-vn/dxsale-sniper-bot#6]
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 209 packages, and audited 210 packages in 1m

**Comment by allenken7** [comment]
also my scss files suddenly stopped compiling to css.

**Comment by mnedelchev-vn** [comment]
Hello, what you're showing is warnings, not errors. I also get bunch of warnings when downloading my packages, but the bot is running. Also what scss files you talking about, the bot has no UX or any front end part. Atm you can run in only via the terminal, you can check your self that the repo does not include any scss or css files. Closing this issue.
